### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by Net-Felix** [dascr/dascr-board#37]
Hi, I'm using Dascr Scorenoard in a docker container (hosted on unraid behind traefik), everything works really well, except sound.
I'm not able to get sound working. even without reverse proxy i cannot get sound working. There are no error messages in the browser console. Should the sounds be played through frontend or backend?

this is my Compose File:
```
version: '3.9'
services:
  backend:
    hostname: dart-backend
    image: ghcr.io/dascr/dascr-board/dascr-board-svc:main
    environment:
      - API_IP=0.0.0.0
      - API_PORT=8000
    networks:
      - traefik
    volumes:
      - /mnt/user/appdata/Dartboard/dascr.db:/dascr.db
      - /mnt/user/appdata/Dartboard/uploads:/uploads
  frontend:
    hostname: dart-frontend
    image: ghcr.io/dascr/dascr-board/dascr-board-ui:main
    environment:
      - VITE_API_BASE=http://10.10.10.40:5051/
      - VITE_API_URL=http://10.10.10.40:5051/api
      - VITE_WS_URL=ws://10.10.10.40:5051/ws
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
```
btw, found a typo (label autoswitch):
```frontend/src/routes/[gameid]/game/GameForm.svelte:218:          <label for="autoswtich" class="flex justify-start items-start">```
should be:
```frontend/src/routes/[gameid]/game/GameForm.svelte:218:          <label for="autoswitch" class="flex justify-start items-start">```
